name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.143.1"
          extended: true

      - name: Build Hugo Site
        run: hugo --minify

      - name: Ensure GitHub Pages compatibility
        run: |
          echo "prachiblogs.com" > public/CNAME  # Set the custom domain
          touch public/.nojekyll  # Disable Jekyll processing

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: prachiblogs.com  # Ensure CNAME is properly set

